import {chromium} from 'file:///C:/Users/felype.souza/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const errors=[]; const report={}; const url=process.argv[2]||'http://127.0.0.1:3011';
await mkdir('output/motion',{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url,{waitUntil:'networkidle'});await page.waitForTimeout(1200);
 assert.equal(await page.locator('html').getAttribute('data-motion'),'full');
 await page.screenshot({path:'output/motion/desktop-hero.png'});
 await page.getByRole('link',{name:'Explore os seminovos',exact:true}).click();await page.waitForTimeout(1100);
 assert.equal(await page.locator('header').getAttribute('data-compact'),'true');
 assert.equal(await page.getByRole('navigation').getByRole('link',{name:'Seminovos',exact:true}).getAttribute('aria-current'),'location');
 await page.getByRole('button',{name:'SUV',exact:true}).click();assert.equal(await page.locator('.vehicle').count(),3);
 const card=page.locator('.vehicle').first();await card.scrollIntoViewIfNeeded();const r=await card.boundingBox();await page.mouse.move(r.x+40,r.y+70);await page.waitForTimeout(350);
 assert.notEqual(await card.evaluate(el=>getComputedStyle(el).transform),'none');
 report.cursor=await page.locator('.cursor-accent').getAttribute('data-mode');assert.equal(report.cursor,'card');
 await page.screenshot({path:'output/motion/desktop-stock.png'});
 await page.getByRole('button',{name:'Todos',exact:true}).click();
 await page.locator('#experiencia').scrollIntoViewIfNeeded();await page.waitForTimeout(800);
 await page.getByRole('button',{name:'Próxima avaliação'}).click();await page.waitForTimeout(700);
 assert.equal(await page.locator('.review-controls > span').innerText(),'2 de 3');
 const review=await page.locator('.review-viewport').boundingBox();await page.mouse.move(review.x+review.width*.8,review.y+70);await page.mouse.down();await page.mouse.move(review.x+review.width*.1,review.y+70,{steps:15});await page.mouse.up();await page.waitForTimeout(1200);
 assert.equal(await page.locator('.review-controls > span').innerText(),'3 de 3');
 await page.screenshot({path:'output/motion/desktop-reviews.png'});
 const bounds=await page.locator('#processo').evaluate(el=>({top:el.getBoundingClientRect().top+scrollY,height:el.offsetHeight}));
 await page.evaluate(({top,height})=>window.scrollTo(0,top-88+(height-innerHeight)*.5),bounds);await page.waitForTimeout(600);
 assert.equal(await page.locator('.journey').getAttribute('data-pinned'),'true');assert.equal(await page.locator('.journey-progress button[aria-pressed=true]').innerText(),'03');
 assert.equal(await page.locator('.steps article:not([inert])').count(),1);
 await page.screenshot({path:'output/motion/desktop-story.png'});
 await page.getByRole('button',{name:'Etapa 5: Comece uma nova história'}).click();await page.waitForTimeout(1100);assert.equal(await page.locator('.journey-progress button[aria-pressed=true]').innerText(),'05');
 report.desktop={activeNav:true,tilt:true,carouselButton:true,carouselDrag:true,stickyStep3:true,step5Button:true};
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url,{waitUntil:'networkidle'});await mobile.waitForTimeout(1200);
 await mobile.getByRole('button',{name:'Abrir menu'}).click();await mobile.getByRole('navigation').getByRole('link',{name:'Seminovos',exact:true}).click();await mobile.waitForTimeout(1000);
 assert.equal(await mobile.getByRole('button',{name:'Abrir menu'}).getAttribute('aria-expanded'),'false');
 assert.equal(await mobile.locator('html').getAttribute('data-fine'),'false');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await mobile.locator('.journey').getAttribute('data-pinned'),'false');
 await mobile.evaluate(()=>scrollTo(0,0));await mobile.waitForTimeout(400);await mobile.screenshot({path:'output/motion/mobile.png',fullPage:true});
 report.mobile={menu:true,noCursor:true,noOverflow:true,linearStory:true};
 await mobile.emulateMedia({reducedMotion:'reduce'});await mobile.waitForTimeout(400);
 assert.equal(await mobile.locator('html').getAttribute('data-motion'),'reduced');
 assert.equal(await mobile.locator('.steps article[inert]').count(),0);
 assert.equal(await mobile.locator('.review-static').count(),1);
 const animations=await mobile.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length);assert.equal(animations,0);
 report.reduced={allStepsReadable:true,allReviewsReadable:true,runningAnimations:animations};
 const noJs=await browser.newPage({viewport:{width:390,height:844},javaScriptEnabled:false});await noJs.goto(url);assert.equal(await noJs.locator('.vehicle').count(),6);assert.equal(await noJs.locator('.steps article').count(),5);report.noJs={contentVisible:true};
 assert.deepEqual(errors,[]);report.pageErrors=errors;
 await writeFile('output/motion/interactions.json',JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close();}
