import {readFile,writeFile} from 'node:fs/promises';
async function edit(file,fn){await writeFile(file,fn(await readFile(file,'utf8')));}
await writeFile('src/lib/vehicles.ts',`import type {Vehicle as DomainVehicle,VehicleImage} from '@/domain/vehicle';
export type Vehicle = Omit<DomainVehicle,'images'|'description'> & {images:VehicleImage[];modelYear:number;mileageKm:number;gallery:string[];description:string;coverImage:string;demo:false};
/** Presentation compatibility only; this module never reads the inventory source. */
export function toVehicleView(vehicle:DomainVehicle):Vehicle{return {...vehicle,images:vehicle.imageDetails,modelYear:vehicle.year,mileageKm:vehicle.mileage,gallery:vehicle.images,coverImage:vehicle.coverImage||vehicle.images[0]||'/brand/m3-logo.webp',description:vehicle.description||(vehicle.make+' '+vehicle.model+' '+vehicle.version+' '+vehicle.year+'. Consulte disponibilidade, documentação e condições com a M3.'),demo:false};}
export {money,number,vehicleName} from './vehicle-format';
`);
await edit('src/lib/vehicle-format.ts',s=>s.replace('export const money =','export const formatPrice =').replace('export const number =','const formatNumber =')+`\nexport const formatMileage=(value:number)=>formatNumber(value)+' km';\nexport const formatYear=(value:number)=>String(value);\n// Existing call sites retain the exact same rendered output.\nexport const money=formatPrice;\nexport const number=formatNumber;\n`);
await edit('src/components/m3/home.tsx',s=>s.replace('import { vehicles, heroVehicle, money } from "@/lib/vehicles";','import { toVehicleView, money } from "@/lib/vehicles";\nimport {getVehicles} from "@/data/vehicles";').replace('export function Home() {','export async function Home() {\n  const vehicles=(await getVehicles()).map(toVehicleView);\n  const heroVehicle=vehicles.find(v=>v.model==="HR-V"&&v.modelYear===2023)!;'));
await edit('src/app/estoque/page.tsx',s=>s.replace('import { vehicles } from "@/lib/vehicles";','import {toVehicleView} from "@/lib/vehicles";\nimport {getVehicles} from "@/data/vehicles";').replace('export default function Page() {','export default async function Page() {\n  const vehicles=(await getVehicles()).map(toVehicleView);'));
await edit('src/app/estoque/[slug]/page.tsx',s=>s.replace('import { vehicles, vehicleName, money, number } from "@/lib/vehicles";','import {toVehicleView, vehicleName, money, number} from "@/lib/vehicles";\nimport {getVehicles,getVehicleBySlug} from "@/data/vehicles";').replace('export const generateStaticParams = () =>\n  vehicles.map((v) => ({ slug: v.slug }));','export const generateStaticParams = async () =>\n  (await getVehicles()).map((v) => ({ slug: v.slug }));').replaceAll('const v = vehicles.find((v) => v.slug === slug);','const record=await getVehicleBySlug(slug);\n  const v=record?toVehicleView(record):null;').replace('  const name = vehicleName(v);','  const vehicles=(await getVehicles()).map(toVehicleView);\n  const name = vehicleName(v);'));
await edit('src/lib/articles.ts',s=>s.replace('import { heroVehicle, vehicles } from "./vehicles";','import {getVehicles} from "@/data/vehicles";').replace('export const articles: Article[] = [','export async function getArticles():Promise<Article[]> {\nconst vehicles=await getVehicles();\nconst heroVehicle=vehicles.find(v=>v.model==="HR-V"&&v.year===2023)!;\nconst articles:Article[] = [').replace('export const articleDate', 'return articles;\n}\nexport const articleDate').replace('image: heroVehicle.coverImage,','image: heroVehicle.coverImage!,').replace('image: vehicles.find((v) => v.model === "Nivus")!.coverImage,','image: vehicles.find((v) => v.model === "Nivus")!.coverImage!,'));
await edit('src/app/blog/page.tsx',s=>s.replace('import { articles }','import { getArticles }').replace('export default function Page() {','export default async function Page() {\n const articles=await getArticles();'));
await edit('src/app/blog/[slug]/page.tsx',s=>s.replace('import { articles, articleDate }','import { getArticles, articleDate }').replace('export const generateStaticParams = () =>\n  articles.map((a) => ({ slug: a.slug }));','export const generateStaticParams = async () =>\n  (await getArticles()).map((a) => ({ slug: a.slug }));').replaceAll('  const { slug } = await params;','  const { slug } = await params;\n  const articles=await getArticles();'));
await edit('src/app/sitemap.ts',s=>s.replace('import { vehicles } from "@/lib/vehicles";','import {getVehicles} from "@/data/vehicles";').replace('import { articles }','import { getArticles }').replace('export default function sitemap(): MetadataRoute.Sitemap {','export default async function sitemap(): Promise<MetadataRoute.Sitemap> {\n const [vehicles,articles]=await Promise.all([getVehicles(),getArticles()]);').replace('vehicles.filter((v) => !v.demo).map','vehicles.map'));
await edit('src/app/opengraph-image.tsx',s=>s.replace('import { heroVehicle } from "@/lib/vehicles";','import {getVehicles} from "@/data/vehicles";\nimport sharp from "sharp";').replace('export default async function Image() {','export default async function Image() {\n const heroVehicle=(await getVehicles()).find(v=>v.model==="HR-V"&&v.year===2023)!;\n const coverImage=heroVehicle.coverImage!;').replaceAll('heroVehicle.coverImage','coverImage').replace('const coverImage=coverImage!;','const coverImage=heroVehicle.coverImage!;').replace('"data:image/webp;base64,"','"data:image/png;base64,"').replace('await readFile(join(process.cwd(), "public", coverImage))','await sharp(await readFile(join(process.cwd(), "public", coverImage))).png().toBuffer()'));
