import {readFile,writeFile} from 'node:fs/promises';
async function edit(path,fn){await writeFile(path,fn(await readFile(path,'utf8')))}
await edit('src/components/m3/primitives.tsx',s=>s.replace("import Image from 'next/image';","export {Photo} from './photo';").replace(/export function Photo\([\s\S]*?\nexport function CTA\(/,'export function CTA('));
await edit('src/components/m3/faq.tsx',s=>s.replace('Este catálogo apresenta veículos de demonstração, com imagens e valores ilustrativos. Consulte a M3 para confirmar o estoque real, as fichas e as condições de venda.','O site apresenta os veículos anunciados pela M3 na última atualização. Como o estoque muda, confirme disponibilidade, preço e informações com a loja antes de visitar.'));
await edit('src/components/m3/service-page.tsx',s=>s.replace('Venda seu carro para a M3 ou use-o como parte de pagamento. Comece com uma conversa e conheça as possibilidades.','Converse com a M3 sobre consignação e avaliação do seu veículo. Conheça as condições e escolha como seguir.').replace('Troca com praticidade','Venda por consignação').replace('Considere seu veículo como parte do pagamento do próximo carro.','Converse sobre anunciar seu veículo com a M3 e confira as condições da consignação.'));
await edit('src/app/contato/page.tsx',s=>s.replace('Conheça nosso perfil no Google','Veja a localização no Google Maps').replace('<a href={dealership.instagram}>','<a href={dealership.instagram} target="_blank" rel="noreferrer">'));
await edit('src/lib/articles.ts',s=>"import {heroVehicle,vehicles} from './vehicles';\n"+s.replace("image:'/reference/dEDaBu6jRucTUjCOt5t3puBWQ.webp'","image:heroVehicle.coverImage").replace("image:'/reference/4oi5yZZLWXhveOmERpd08vztqpA.png'","image:vehicles.find(v=>v.model==='Nivus')!.coverImage"));
await edit('src/components/m3/legal-page.tsx',s=>s.replace('15 SET 2026','18 SET 2026').replace('Catálogo de demonstração','Informações do estoque').replace('Os veículos identificados como demonstração usam imagens e dados ilustrativos. Não representam estoque ativo confirmado nem proposta comercial.','O catálogo reúne os anúncios públicos da M3 consultados na data indicada em cada ficha. O estoque pode mudar entre atualizações.').replace('Fotografias ilustrativas e retratos não representam necessariamente o estoque, clientes ou colaboradores da M3.','As fotos do catálogo vêm dos anúncios dos respectivos veículos. Fotografias editoriais genéricas de serviços são identificadas como ilustrativas.').replace('As fotografias e fontes usadas nesta versão são servidas pelo próprio site.','As fontes são locais. Fotografias de anúncios podem ser obtidas do fornecedor Usadosbr pelo servidor de imagens.').replace('A busca e os filtros usam o estado da página.','A busca e os filtros usam a URL da página para permitir compartilhar resultados.'));
await edit('src/components/m3/lead-form.tsx',s=>s.replace("type Kind=","import {prepareLead} from '@/lib/lead';\ntype Kind=").replace("const [draft,setDraft]=useState('');","const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');").replace('onSubmit={e=>{','onSubmit={async e=>{').replace("const lines=[", "setBusy(true);setError('');const lines=[").replace("key!=='ciência'&&", "key!=='ciência'&&key!=='website'&&").replace("setDraft(lines.join('\\n'));requestAnimationFrame(()=>review.current?.focus())", "try{const result=await prepareLead({name:String(values.get('Nome')||''),phone:String(values.get('Telefone')||''),email:String(values.get('E-mail')||''),type:kind==='trade'?'trade_in':kind==='finance'?'financing':'contact',consent:values.has('ciência'),createdAt:new Date().toISOString()},lines.join('\\n'),String(values.get('website')||''));setDraft(result.draft);requestAnimationFrame(()=>review.current?.focus())}catch(err){setError(err instanceof Error?err.message:'Não foi possível preparar a mensagem. Tente novamente.')}finally{setBusy(false)}").replace('<div className="form-grid">','<div className="sr-only" aria-hidden="true"><label>Deixe vazio<input name="website" tabIndex={-1} autoComplete="off"/></label></div><div className="form-grid">').replace('<button type="submit" className="form-submit">Revisar e continuar','{error&&<p role="alert">{error}</p>}<button type="submit" className="form-submit" disabled={busy} aria-busy={busy}>{busy?\'Preparando…\':\'Revisar e continuar\'}').replace('<h3>Revise sua mensagem</h3>','<p role="status">Mensagem preparada. Revise antes de abrir o WhatsApp.</p><h3>Revise sua mensagem</h3>'));
