import {chromium} from 'file:///C:/Users/felype.souza/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:3002';const out='output/playwright/m3-production';await mkdir(out,{recursive:true});
const {vehicles}=JSON.parse(await readFile('src/data/vehicles.generated.json','utf8'));const hero=vehicles.find(v=>v.model==='HR-V'&&v.modelYear===2023);const widths=[[360,800],[375,812],[390,844],[430,932],[768,1024],[1024,768],[1280,800],[1366,768],[1440,900],[1920,1080]];
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({reducedMotion:'reduce'});const errors=[],report=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
async function visit(route){const r=await page.goto(base+route,{waitUntil:'networkidle',timeout:60000});return r.status();}
async function check(route,w,h,screenshot=true){await page.setViewportSize({width:w,height:h});const status=await visit(route);await page.evaluate(async()=>{await document.fonts.ready;for(const image of document.images)if(image.loading!=='lazy')await image.decode().catch(()=>{});});const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src),h1:document.querySelectorAll('h1').length}));if(screenshot)await page.screenshot({path:out+'/'+(route==='/'?'home':route.replaceAll('/','_'))+'-'+w+'.png',fullPage:true});report.push({route,w,h,status,...metrics});assert.equal(status,200,route);assert.equal(metrics.overflow,false,route+' overflow '+w);assert.equal(metrics.h1,1,route+' h1');assert.deepEqual(metrics.broken,[],route+' images');}
try{
for(const [w,h] of widths){for(const route of ['/','/estoque','/estoque/'+hero.slug,'/contato'])await check(route,w,h);console.log('viewport',w,'passed');}
await page.setViewportSize({width:1440,height:900});await visit('/estoque');await page.getByRole('searchbox').fill('HRV');assert.equal(await page.locator('.vehicle-card').count(),2);await page.getByLabel('Ano',{exact:true}).selectOption('2023');assert.equal(await page.locator('.vehicle-card').count(),1);assert.ok(page.url().includes('busca=HRV'));await page.goBack();assert.equal(await page.locator('.vehicle-card').count(),2);await page.goForward();assert.equal(await page.locator('.vehicle-card').count(),1);await page.getByRole('button',{name:'Limpar filtros'}).click();await page.getByLabel('Ordenar veículos').selectOption('price-asc');assert.ok((await page.locator('.vehicle-card').first().innerText()).includes('Fusca'));
await visit('/estoque/'+hero.slug);const wa=await page.getByRole('link',{name:'Tenho interesse'}).getAttribute('href');assert.equal(new URL(wa).pathname,'/5511930055771');assert.ok(new URL(wa).searchParams.get('text').includes('HR-V'));await page.getByRole('button',{name:'Próxima imagem',exact:true}).click();assert.ok((await page.locator('.gallery-caption').innerText()).includes('Imagem 2'));
await page.setViewportSize({width:390,height:844});await visit('/');await page.getByRole('button',{name:'Abrir menu'}).click();assert.equal(await page.getByRole('button',{name:'Fechar menu'}).getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Abrir menu'}).getAttribute('aria-expanded'),'false');await visit('/estoque');await page.getByRole('button',{name:'Filtrar veículos'}).click();assert.ok(await page.getByRole('searchbox').isVisible());
await visit('/contato');await page.getByRole('button',{name:'Revisar e continuar'}).click();assert.equal(await page.locator('.form-review').count(),0);await page.getByLabel('Nome',{exact:true}).fill('Teste local');await page.getByLabel('Telefone',{exact:true}).fill('(11) 99999-0000');await page.getByLabel('Interesse',{exact:true}).selectOption('Comprar um carro');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Revisar e continuar'}).click();await page.locator('.form-review').waitFor();assert.ok((await page.getByRole('link',{name:'Abrir no WhatsApp'}).getAttribute('href')).includes('wa.me'));await page.getByLabel('Nome',{exact:true}).fill('Teste corrigido');assert.equal(await page.locator('.form-review').count(),0);
for(const route of ['/venda-seu-carro','/financiamento','/sobre','/blog','/privacidade','/cookies','/termos'])for(const w of [390,1440])await check(route,w,w===390?844:900);
for(const v of vehicles){assert.equal(await visit('/estoque/'+v.slug),200);assert.ok((await page.locator('h1').innerText()).includes(v.model));}
assert.equal(await visit('/estoque/veiculo-inexistente'),404);assert.ok(await page.getByRole('link',{name:'Voltar ao início'}).isVisible());
assert.deepEqual(errors,[],'Browser errors');console.log('All flows passed; no messages submitted.');
}finally{await writeFile(out+'/report.json',JSON.stringify({generatedAt:new Date().toISOString(),report,errors},null,2));await browser.close();}
